user-api:     uvicorn services.user-api.app.main:app --reload --port 8000
resume-parser: uvicorn services.resume-parser.app.main:app --reload --port 8001
# web-crawler:  uvicorn services.web-crawler.main:app --reload --port 8002