user-api:     uvicorn services.user-api.app.main:app --reload --port 8000
resume-parser: uvicorn services.resume-parser.app.main:app --reload --port 8001
recommendation-service:  uvicorn services.recommendation-service.app.main:app --reload --port 8002